services:
  db:
    image: postgres:14
    restart: always
    secrets:
      - postgres-db
      - postgres-psw
      - postgres-user
    volumes:
      - db-filesystem:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB_FILE=/run/secrets/postgres-db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-psw
      - POSTGRES_USER_FILE=/run/secrets/postgres-user
    ports:
      - "5432:5432"
  
volumes:
  db-filesystem:

secrets:
  postgres-db:
    file: credentials/dev/.postgres.db
  postgres-psw:
    file: credentials/dev/.postgres.psw
  postgres-user:
    file: credentials/dev/.postgres.user